apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-broadcaster
  namespace: todo-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-project-broadcaster
  template:
    metadata:
      labels:
        app: todo-project-broadcaster
    spec:
      containers:
        - name: todo-project-broadcaster
          image: IMAGE_PLACEHOLDER
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: NATS_CHANNEL
              value: todos
            - name: NATS_GROUP
              value: nats_subscribers
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: broadcaster
                  key: API_KEY
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster
                  key: CHAT_ID
          resources:
            limits:
              cpu: "10m"
              memory: "20Mi"