apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-broadcaster
  namespace: todo-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-project-broadcaster
  template:
    metadata:
      labels:
        app: todo-project-broadcaster
    spec:
      containers:
      - env:
        - name: NATS_URL
          value: nats://my-nats:4222
        - name: NATS_CHANNEL
          value: todos
        - name: NATS_GROUP
          value: nats_subscribers
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: API_KEY
              name: broadcaster
        - name: CHAT_ID
          valueFrom:
            secretKeyRef:
              key: CHAT_ID
              name: broadcaster
        image: pasiol/subscriber-bot@sha256:e39f4adbe4217040add800c2845c578ff1d52196d26959b7e0735e7f33fd64c7
        name: todo-project-broadcaster
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
---